version: '3.8'
services:
  app:
    build:
      context: ../quickcart
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quickcart_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath:data.sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - springboot-mysql-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=quickcart_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    name: springboot-mysql-network

volumes:
  mysql-data: